### ISSUE TITLE
同花顺概念问题

### ISSUE THREAD

**Issue by shepherdshaha** [liudengfeng/cswd#2]
问题还是存在，代码现在是从
http://basic.10jqka.com.cn/
采集同花顺概念，像win8概念、3G、4G概念早已过时，请查看:
cswd\websource\ths.py文件
第120行
self.host_url = 'http://basic.10jqka.com.cn/'
第323行~第343行的 def get_category_dataframe(self)方法。
应该是从
http://q.10jqka.com.cn/gn/
采集。

**Comment by liudengfeng** [comment]
我在测试，马上上传

**Comment by liudengfeng** [comment]
您对投资组合优化有没有研究，zipline中有关组合优化问题，我正在弄，有兴趣的话一起整整？

**Comment by liudengfeng** [comment]
加油。我也是业余爱好。同花顺问题依然存在，正在排查

**Comment by liudengfeng** [comment]
搞定
